# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aa2601c26caabab555db989d0d731b4933e1c9fbbcbe858331940ac3b502bf9fe2e3e5c2228619ce5fd5e357fbfa4cd0bdb282f791df4be33520d0d1cc29512

test:
  secret_key_base: 08c5edd6bc726c3cff352d6644e210a9c07e53bb90c4d49a2a838988333031c13729e7c379eebc3b422fc650b91fbbb43f74af1852252609b0a6598f954a24ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
